language: node_js
sudo: false
matrix:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "4"
    - node_js: "5"
  fast_finish: true
env:
  - "NODE_FLAGS='' SCRIPT_FLAGS=''"
before_script:
- git submodule update --init --recursive
script: "npm run build && npm run test"
branches:
  only:
    - master